const MEMBERS = [
  { name: "Afrillyana Moligay", img: "afrillyana_moligay.jpg" },
  { name: "Alfa Nofario", img: "alfa_nofario.jpg" },
  { name: "Anjela Merici", img: "anjela_merici.jpg" },
  { name: "Celsi Apriani", img: "celsi_apriani.jpg" },
  { name: "Dhion Maasi", img: "dhion_maasi.jpg" },
  { name: "Efraim Monulunan", img: "efraim_monulunan.jpg" },
  { name: "Elen Banetan", img: "elen_banetan.jpg" },
  { name: "Elna Elna", img: "elna_elna.jpg" },
  { name: "Elsa Tirena", img: "elsa_tirena.jpg" },
  { name: "Elvi Latunda", img: "elvi_latunda.jpg" },
  { name: "Fendri siamo Fendi", img: "fendri_siamo_fendi.jpg" },
  { name: "Fikran Taherr", img: "fikran_taherr.jpg" },
  { name: "Inkasari Lalio", img: "inkasari_lalio.jpg" },
  { name: "Jeliana Pingkan", img: "jeliana_pingkan.jpg" },
  { name: "Juan Marcello Lahundo", img: "juan_marcello_lahundo.jpg" },
  { name: "Juniverlita Tundoon", img: "juniverlita_tundoon.jpg" },
  { name: "Kang Copet", img: "kang_copet.jpg" },
  { name: "Lena Vivo", img: "lena_vivo.jpg" },
  { name: "Meilani Kristin Potindingo", img: "meilani_kristin_potindingo.jpg" },
  { name: "Nadia Renata", img: "nadia_renata.jpg" },
  { name: "Novry Gabrielo", img: "novry_gabrielo.jpg" },
  { name: "Pikaa", img: "pikaa.jpg" },
  { name: "Prilawati Sasube", img: "prilawati_sasube.jpg" },
  { name: "Rio Fransisco", img: "rio_fransisco.jpg" },
  { name: "Sidon Mbesanggene", img: "sidon_mbesanggene.jpg" },
  { name: "Welong Nathasya", img: "welong_nathasya.jpg" },
  { name: "Wiwin Saong", img: "wiwin_saong.jpg" },
  { name: "Yolanda Pasondek", img: "yolanda_pasondek.jpg" },
  { name: "Yuni Meaa", img: "yuni_meaa.jpg" },
];
