const MEMBERS = [
  { name: "Afrillyana Moligay", img: "photos/afrillyana_moligay.jpg" },
  { name: "Alfa Nofario", img: "photos/alfa_nofario.jpg" },
  { name: "Anjela Merici", img: "photos/anjela_merici.jpg" },
  { name: "Celsi Apriani", img: "photos/celsi_apriani.jpg" },
  { name: "Dhion Maasi", img: "photos/dhion_maasi.jpg" },
  { name: "Efraim Monulunan", img: "photos/efraim_monulunan.jpg" },
  { name: "Elen Banetan", img: "photos/elen_banetan.jpg" },
  { name: "Elna Elna", img: "photos/elna_elna.jpg" },
  { name: "Elsa Tirena", img: "photos/elsa_tirena.jpg" },
  { name: "Elvi Latunda", img: "photos/elvi_latunda.jpg" },
  { name: "Fendri siamo Fendi", img: "photos/fendri_siamo_fendi.jpg" },
  { name: "Fikran Taherr", img: "photos/fikran_taherr.jpg" },
  { name: "Inkasari Lalio", img: "photos/inkasari_lalio.jpg" },
  { name: "Jeliana Pingkan", img: "photos/jeliana_pingkan.jpg" },
  { name: "Juan Marcello Lahundo", img: "photos/juan_marcello_lahundo.jpg" },
  { name: "Juniverlita Tundoon", img: "photos/juniverlita_tundoon.jpg" },
  { name: "Kang Copet", img: "photos/kang_copet.jpg" },
  { name: "Lena Vivo", img: "photos/lena_vivo.jpg" },
  { name: "Meilani Kristin Potindingo", img: "photos/meilani_kristin_potindingo.jpg" },
  { name: "Nadia Renata", img: "photos/nadia_renata.jpg" },
  { name: "Novry Gabrielo", img: "photos/novry_gabrielo.jpg" },
  { name: "Pikaa", img: "photos/pikaa.jpg" },
  { name: "Prilawati Sasube", img: "photos/prilawati_sasube.jpg" },
  { name: "Rio Fransisco", img: "photos/rio_fransisco.jpg" },
  { name: "Sidon Mbesanggene", img: "photos/sidon_mbesanggene.jpg" },
  { name: "Welong Nathasya", img: "photos/welong_nathasya.jpg" },
  { name: "Wiwin Saong", img: "photos/wiwin_saong.jpg" },
  { name: "Yolanda Pasondek", img: "photos/yolanda_pasondek.jpg" },
  { name: "Yuni Meaa", img: "photos/yuni_meaa.jpg" },
];
