const MEMBERS = [
  { name: "Afrillyana Moligay", img: "afrillyana_moligay.jpg" },
  { name: "Alfa Nofario", img: "alfa_nofario.jpg" },
  { name: "Anjela Merici", img: "anjela_merici.jpg" },
  { name: "Chelsea Apriani", img: "celsi_apriani.jpg" },
  { name: "Dhion Maasi", img: "dhion_maasi.jpg" },
  { name: "Efraim Monulunan", img: "efraim_monulunan.jpg" },
  { name: "Elen Banetan", img: "elen_banetan.jpg" },
  { name: "Elnamerna Daman", img: "elna_elna.jpg" },
  { name: "Elsa Tirena", img: "elsa_tirena.jpg" },
  { name: "Elvi Latunda", img: "elvi_latunda.jpg" },
  { name: "Mardila Lakatan", img: "fendri_siamo_fendi.jpg" },
  { name: "Fikran Sinaling", img: "fikran_taherr.jpg" },
  { name: "Inkasari Lalio", img: "inkasari_lalio.jpg" },
  { name: "Jeliana Pingkan", img: "jeliana_pingkan.jpg" },
  { name: "Juan Marcello Lahundo", img: "juan_marcello_lahundo.jpg" },
  { name: "Juniverlita Tundoon", img: "juniverlita_tundoon.jpg" },
  { name: "Billy W Lapaso", img: "kang_copet.jpg" },
  { name: "Lena Kamay", img: "lena_vivo.jpg" },
  { name: "Meilani Kristin Potindingo", img: "meilani_kristin_potindingo.jpg" },
  { name: "Rolan Sambaulu", img: "nadia_renata.jpg" },
  { name: "Novryadi Gabrielo", img: "novry_gabrielo.jpg" },
  { name: "Priskila Yadaul", img: "pikaa.jpg" },
  { name: "Prilawati Sasube", img: "prilawati_sasube.jpg" },
  { name: "Rio Fransisco", img: "rio_fransisco.jpg" },
  { name: "Sidon Mbesanggene", img: "sidon_mbesanggene.jpg" },
  { name: "Nathasya A. Welong", img: "welong_nathasya.jpg" },
  { name: "Wiwin Saong", img: "wiwin_saong.jpg" },
  { name: "Yolanda Pasondek", img: "yolanda_pasondek.jpg" },
  { name: "Reno Baideng", img: "yuni_meaa.jpg" },
];
